# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/russell/code/arm/smartrain2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/russell/code/arm/smartrain2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/russell/code/arm/smartrain2/CMakeFiles /home/russell/code/arm/smartrain2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/russell/code/arm/smartrain2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smartrain

# Build rule for target.
smartrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smartrain
.PHONY : smartrain

# fast build rule for target.
smartrain/fast:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/build
.PHONY : smartrain/fast

src/EventLogger.o: src/EventLogger.cpp.o

.PHONY : src/EventLogger.o

# target to build an object file
src/EventLogger.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/EventLogger.cpp.o
.PHONY : src/EventLogger.cpp.o

src/EventLogger.i: src/EventLogger.cpp.i

.PHONY : src/EventLogger.i

# target to preprocess a source file
src/EventLogger.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/EventLogger.cpp.i
.PHONY : src/EventLogger.cpp.i

src/EventLogger.s: src/EventLogger.cpp.s

.PHONY : src/EventLogger.s

# target to generate assembly for a file
src/EventLogger.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/EventLogger.cpp.s
.PHONY : src/EventLogger.cpp.s

src/LCD.o: src/LCD.cpp.o

.PHONY : src/LCD.o

# target to build an object file
src/LCD.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/LCD.cpp.o
.PHONY : src/LCD.cpp.o

src/LCD.i: src/LCD.cpp.i

.PHONY : src/LCD.i

# target to preprocess a source file
src/LCD.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/LCD.cpp.i
.PHONY : src/LCD.cpp.i

src/LCD.s: src/LCD.cpp.s

.PHONY : src/LCD.s

# target to generate assembly for a file
src/LCD.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/LCD.cpp.s
.PHONY : src/LCD.cpp.s

src/NetworkInfo.o: src/NetworkInfo.cpp.o

.PHONY : src/NetworkInfo.o

# target to build an object file
src/NetworkInfo.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/NetworkInfo.cpp.o
.PHONY : src/NetworkInfo.cpp.o

src/NetworkInfo.i: src/NetworkInfo.cpp.i

.PHONY : src/NetworkInfo.i

# target to preprocess a source file
src/NetworkInfo.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/NetworkInfo.cpp.i
.PHONY : src/NetworkInfo.cpp.i

src/NetworkInfo.s: src/NetworkInfo.cpp.s

.PHONY : src/NetworkInfo.s

# target to generate assembly for a file
src/NetworkInfo.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/NetworkInfo.cpp.s
.PHONY : src/NetworkInfo.cpp.s

src/RelayController.o: src/RelayController.cpp.o

.PHONY : src/RelayController.o

# target to build an object file
src/RelayController.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/RelayController.cpp.o
.PHONY : src/RelayController.cpp.o

src/RelayController.i: src/RelayController.cpp.i

.PHONY : src/RelayController.i

# target to preprocess a source file
src/RelayController.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/RelayController.cpp.i
.PHONY : src/RelayController.cpp.i

src/RelayController.s: src/RelayController.cpp.s

.PHONY : src/RelayController.s

# target to generate assembly for a file
src/RelayController.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/RelayController.cpp.s
.PHONY : src/RelayController.cpp.s

src/SmartRain.o: src/SmartRain.cpp.o

.PHONY : src/SmartRain.o

# target to build an object file
src/SmartRain.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/SmartRain.cpp.o
.PHONY : src/SmartRain.cpp.o

src/SmartRain.i: src/SmartRain.cpp.i

.PHONY : src/SmartRain.i

# target to preprocess a source file
src/SmartRain.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/SmartRain.cpp.i
.PHONY : src/SmartRain.cpp.i

src/SmartRain.s: src/SmartRain.cpp.s

.PHONY : src/SmartRain.s

# target to generate assembly for a file
src/SmartRain.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/SmartRain.cpp.s
.PHONY : src/SmartRain.cpp.s

src/WeatherService.o: src/WeatherService.cpp.o

.PHONY : src/WeatherService.o

# target to build an object file
src/WeatherService.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/WeatherService.cpp.o
.PHONY : src/WeatherService.cpp.o

src/WeatherService.i: src/WeatherService.cpp.i

.PHONY : src/WeatherService.i

# target to preprocess a source file
src/WeatherService.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/WeatherService.cpp.i
.PHONY : src/WeatherService.cpp.i

src/WeatherService.s: src/WeatherService.cpp.s

.PHONY : src/WeatherService.s

# target to generate assembly for a file
src/WeatherService.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/WeatherService.cpp.s
.PHONY : src/WeatherService.cpp.s

src/settings.o: src/settings.cpp.o

.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i

.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s

.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/smartrain.dir/build.make CMakeFiles/smartrain.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... smartrain"
	@echo "... edit_cache"
	@echo "... src/EventLogger.o"
	@echo "... src/EventLogger.i"
	@echo "... src/EventLogger.s"
	@echo "... src/LCD.o"
	@echo "... src/LCD.i"
	@echo "... src/LCD.s"
	@echo "... src/NetworkInfo.o"
	@echo "... src/NetworkInfo.i"
	@echo "... src/NetworkInfo.s"
	@echo "... src/RelayController.o"
	@echo "... src/RelayController.i"
	@echo "... src/RelayController.s"
	@echo "... src/SmartRain.o"
	@echo "... src/SmartRain.i"
	@echo "... src/SmartRain.s"
	@echo "... src/WeatherService.o"
	@echo "... src/WeatherService.i"
	@echo "... src/WeatherService.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

